import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { cn } from "@/lib/utils"

import "./globals.css"
import { QueryProvider } from "@/components/query-provider"

const fontSans = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased min-h-screen", fontSans.className)}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
